[[manager.prepend_keymap]]
on   = "H"
run  = 'hidden --toggle'
desc = "Toggle hidden files with shift+h"

[[manager.prepend_keymap]]
on   = "T"
run  = "plugin --sync max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"
