import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[shell]
program = "/bin/zsh"

[window]
padding = { x = 10, y = 10 }
decorations = "None"
option_as_alt = "Both"
startup_mode = "Maximized"

[font]
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
size = 13

[env]
TERM = "xterm-256color"

